### Login admin (Obtener token nuevo)
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "AnaMartinez@gmail.com",
    "password": "anamart123"
}

### Login usuario corriente (Obtener token nuevo)
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "LuisGomez@gmail.com",
    "password": "Lg0m3z"
}

### Login usuario corriente (No verificado)
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "jhernandez19@outlook.com",
    "password": "jhndez1234"
}

### Verificar usuario
POST http://localhost:3000/users/verificar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NzQwNzM5LCJleHAiOjE3NDQ3NDI1Mzl9.TS9kt8gqRzaKKu687xxpL_etUTVPpHk86AmsPO9Z1L4

{
    "id": "A9386387-73A4-4C94-BA8D-3B2F7DE452C4"
}

### Login usuario corriente (No verificado)
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "errbaraho2@gmail.com",
    "password": "EnrriqBarr@123"
}
### Registrar un nuevo usuario 
POST http://localhost:3000/register
Content-Type: application/json

{
    "nombre": "Enrique Barahona",
    "email": "errbaraho2@gmail.com",
    "password": "EnrriqBarr@123"
}

### Registrar un nuevo usuario (con rol admin)
POST http://localhost:3000/registerAdmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NTk0NDc5LCJleHAiOjE3NDQ1OTYyNzl9.s7E7oSPKBNJSBV0ZsoLGJTbEnMDH4pv_dkdloAZnLBA

{
    "nombre": "Tulio Gonzalez",
    "email": "tlgonzalez22@hotmail.com",
    "password": "TulioGonzalez123",
    "rol": "Admin",
    "verificado": 1
}

### Obtener IDs de usuarios (para usar en solicitudes)
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NzQ0MjY4LCJleHAiOjE3NDQ3NDYwNjh9._XYaIZiIdJYM-yUzr9smdgEaWtJfeEqXzijqgzTGxoM

### GET PARA LIBROS con filtros
GET http://localhost:3000/libros?genre=Realismo%magico&author=Isabel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NjkwODY1LCJleHAiOjE3NDQ2OTI2NjV9.hXZyN4V2PqgvNWc8tmu-33WddwhOZeaQVSmHh5MuHik

### GET PARA LIBROS
GET http://localhost:3000/libros
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NjkwODY1LCJleHAiOjE3NDQ2OTI2NjV9.hXZyN4V2PqgvNWc8tmu-33WddwhOZeaQVSmHh5MuHik


### GET UN LIBRO POR ID 
GET http://localhost:3000/libros/5A07E00B-99B0-45EC-A7F7-1771D5EB1A6C
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NjkwODY1LCJleHAiOjE3NDQ2OTI2NjV9.hXZyN4V2PqgvNWc8tmu-33WddwhOZeaQVSmHh5MuHik

### CREAR UN NUEVO LIBRO
POST http://localhost:3000/libros
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NjY0NTk1LCJleHAiOjE3NDQ2NjYzOTV9.gPZGeOrq7a8fmnE-ivYZ2TEK92yDYkYuWpDEMZ4vRpE

{
    "nombre": "Crónica de una muerte anunciada",
    "autor": "Gabriel Garcia Marquez",
    "editorial": "Penguin Random House",
    "estado": "Disponible",
    "rating": 4.5,
    "paginas": 120,
    "idioma": "Español",
    "descripcion": "Novela corta que relata el asesinato de Santiago Nasar a manos de los hermanos Vicario.",
    "fecha_publicacion": "1981-01-01"
}

### ELIMINAR UN LIBRO 
DELETE http://localhost:3000/libros/B8DAD52C-3E6D-4B63-840B-CA419D34377E
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0Njc5ODU0LCJleHAiOjE3NDQ2ODE2NTR9.54EBqvuhX2RV_ervwALruv7zOBkV2puBADbTRrUwgTA

### SOLICITAR UN LIBRO (usar un ID de usuario real de la BD) (Esta solicitud se manda a la tabla de solicitudes)
POST http://localhost:3000/libros/8AD55DF0-E102-4B35-A7CE-A360A3C7F295/solicitar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsIlJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NDk1Njg3LCJleHAiOjE3NDQ0OTc0ODd9.LHCq3Pk2TocJXnXv52LzHBX4u8UAK63bEi06gUk0T3s

{
    "usuarioId": "0E4E5E0685D76B4F88FCE28FE17D36A1"
}

### VER TODAS LAS SOLICITUDES (solo admins)(Desoues de realizar la solicitud de un libro, se usa esta ruta para ver las solictudes pendientes)
GET http://localhost:3000/libros/solicitudes/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsIlJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NDk5MDQxLCJleHAiOjE3NDQ1MDA4NDF9.GQWfPczkmuJM2xR-0CrwoQti0rLpGz9LDkswx9kPc0o

### Actualizar estado de una solicitud (solo admins) (Despues de verificaer la solicitudes pendientes, se usa esta ruta para actualizar el estado del libro
###Si en la tabla dice que esta disbonible, se cambia a prestado y viceversa y se pone el id de la solicitud, para eliminarla)
PATCH http://localhost:3000/libros/estado/8AD55DF0-E102-4B35-A7CE-A360A3C7F295
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsIlJvbCI6IkFkbWluIiwiaWF0IjoxNzQzNjcxMzQ1LCJleHAiOjE3NDM2NzMxNDV9.gxXVLevK2bwPsoEJ2ZQkd3sXv1ZJbPSYoYuvSvI60F8

{
    "estado": "Disponible",
    "solicitudId": 2
}

### Ver historial de eventos (solo admins)
GET http://localhost:3000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NjkwODY1LCJleHAiOjE3NDQ2OTI2NjV9.hXZyN4V2PqgvNWc8tmu-33WddwhOZeaQVSmHh5MuHik

### Ver historial de eventos de un usuario (solo admins)
GET http://localhost:3000/logs/065E4E0E-D785-4F6B-88FC-E28FE17D36A1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NjkwODY1LCJleHAiOjE3NDQ2OTI2NjV9.hXZyN4V2PqgvNWc8tmu-33WddwhOZeaQVSmHh5MuHik

### Crear un nuevo autor
POST http://localhost:3000/libros/author
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NzUwMDAzLCJleHAiOjE3NDQ3NTE4MDN9.T8Ooinst8L291SwvT3GfH0X8oi6rlZXRRtgaAQX3oOw

{
    "nombre": "Fulano",
    "apellido": "de Tal",
    "nacionalidad": "MXN",
    "fecha_nacimiento": "1990-01-01"
}

### Crear una editorial
POST http://localhost:3000/libros/editorial
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ0NzUwMDAzLCJleHAiOjE3NDQ3NTE4MDN9.T8Ooinst8L291SwvT3GfH0X8oi6rlZXRRtgaAQX3oOw

{
    "nombre": "HarperCollins",
    "pais": "Reino Unido"
}