
### Pruebas de API para la gestión de libros, solicitudes e historial de eventos

### GET PARA LIBROS
GET http://localhost:3000/libros
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

### GET PARA LIBROS con filtros
GET http://localhost:3000/libros?genre=Realismo%mágico&author=Isabel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

### GET UN LIBRO POR ID 
GET http://localhost:3000/libros/9F0EA9B8-83E6-4D55-B67D-4E418466DC80
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

### CREAR UN NUEVO LIBRO (EL AUTOR Y LA EDITORIAL DEBEN EXISTIR EN LA BD)
POST http://localhost:3000/libros
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "nombre": "Crónica de una muerte anunciada",
    "autor": "Gabriel Garcia Marquez",
    "editorial": "Penguin Random House",
    "estado": "Disponible",
    "rating": 4.5,
    "paginas": 120,
    "idioma": "Español",
    "descripcion": "Novela corta que relata el asesinato de Santiago Nasar a manos de los hermanos Vicario.",
    "fecha_publicacion": "1981-01-01"
}

### Crear otro libro
POST http://localhost:3000/libros
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "nombre": "Sofia Sofia",
    "autor": "Isabel Allende",
    "editorial": "HarperCollins",
    "estado": "Disponible",
    "rating": 4.5,
    "paginas": 120,
    "idioma": "Español",
    "descripcion": "Novela corta que relata la vida de una mujer en un mundo de hombres.",
    "fecha_publicacion": "2023-01-01"
}

### Actualizar un libro (PATCH)
PATCH http://localhost:3000/libros/5A07E00B-99B0-45EC-A7F7-1771D5EB1A6C
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "rating": 4.0
}

### ELIMINAR UN LIBRO 
DELETE http://localhost:3000/libros/9F433BF7-7A36-46C9-AC75-7AAE8F6BCA57
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

### SOLICITAR UN LIBRO (usar un ID de usuario real de la BD) (Esta solicitud se manda a la tabla de solicitudes)
POST http://localhost:3000/libros/solicitar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "id": "688CCE10-D595-407E-A46E-94D0E2B84E4F"
}

### VER TODAS LAS SOLICITUDES (solo admins)(Desoues de realizar la solicitud de un libro, se usa esta ruta para ver las solictudes pendientes)
GET http://localhost:3000/libros/solicitudes/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

### Actualizar estado de una solicitud (solo admins) (Despues de verificaer la solicitudes pendientes, se usa esta ruta para actualizar el estado del libro
###Si en la tabla dice que esta disbonible, se cambia a prestado y viceversa y se pone el id de la solicitud, para eliminarla)
PATCH http://localhost:3000/libros/estado
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "solicitudId": 13,
    "estado": "Disponible",
    "libroID": "9F0EA9B8-83E6-4D55-B67D-4E418466DC80"
}

### Ver historial de eventos (solo admins)
GET http://localhost:3000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MTE3Mzk0LCJleHAiOjE3NDUxMTkxOTR9.23lwxSoc1mVkMrjhuzJ2wDOojo9001Mri808q81Zm6w

### Ver historial de eventos de un usuario (solo admins)
GET http://localhost:3000/logs/065E4E0E-D785-4F6B-88FC-E28FE17D36A2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MTE3Mzk0LCJleHAiOjE3NDUxMTkxOTR9.23lwxSoc1mVkMrjhuzJ2wDOojo9001Mri808q81Zm6w

### Crear un nuevo autor
POST http://localhost:3000/libros/author
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "nombre": "Charles",
    "apellido": "Bukowski",
    "nacionalidad": "DEU",
    "fecha_nacimiento": "1994-03-09"
}

### Crear una editorial
POST http://localhost:3000/libros/editorial
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "nombre": "HarperCollins",
    "pais": "Reino Unido"
}

### Actualizar un libro
PUT http://localhost:3000/libros/E25BD787-39F5-48CB-ACEE-27004E4258C7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFuYU1hcnRpbmV6QGdtYWlsLmNvbSIsInJvbCI6IkFkbWluIiwiaWF0IjoxNzQ1MDk0MzgxLCJleHAiOjE3NDUwOTYxODF9.O2dUp9dvTQjJVuFxPbN2aFDulE_AQnLviYasfeAuPDs

{
    "nombre": "Crónica de una muerte anunciada",
    "autor": "Gabriel Garcia Marquez",
    "editorial": "Penguin Random House",
    "rating": 4.5,
    "descripcion": "Novela corta que relata el asesinato de Santiago Nasar a manos de los hermanos Vicario.",
    "fecha_publicacion": "1981-01-01T00:00:00.000Z",
    "paginas": 120,
    "idioma": "Español",
    "generos" : [
        "Ficción",
        "Novela"
    ]
}